services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD","ollama","list"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s

  api:
    build:
      context: ./fastapi
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_EMBED_MODEL=embeddinggemma:latest
      - OLLAMA_GEN_MODEL=llama3.2:latest
      - LANCEDB_URI=/data/lancedb
      - CHUNK_SIZE=1200
      - CHUNK_OVERLAP=200
    volumes:
      - lancedb:/data
    ports:
      - "8000:8000"

  app:
    build:
      context: ./app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LANCEDB_URI=/data/lancedb
    volumes:
      - lancedb:/data
    ports:
      - "8501:8501"

volumes:
  ollama:
  lancedb:
