services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11434:11434"]
    environment:
      - OLLAMA_NO_GPU=1       # <-- CPU mode by default
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: rag-api
    env_file: [.env]
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      # (… your other envs …)
    ports: ["8000:8000"]
    volumes:
      - lancedb:/data/lancedb
      - docling_cache:/root/.cache
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama:
  lancedb:
  faiss_index: 
  docling_cache:
